/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-07-06 04:42:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1675922414281L));
    _jspx_dependants.put("jar:file:/C:/Users/rsm50/Desktop/idle/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/finalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>상품 등록</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("  	<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\" integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js\" integrity=\"sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	$(function() {\r\n");
      out.write("\r\n");
      out.write("		let fileInput = document.getElementById('multipartFiles');\r\n");
      out.write("		let max = 3;\r\n");
      out.write("\r\n");
      out.write("		fileInput.addEventListener('change', function(event) {\r\n");
      out.write("			if (event.target.files.length > max) {\r\n");
      out.write("				alert('최대 ' + max + '개 까지만 선택할 수 있습니다.');\r\n");
      out.write("				fileInput.value = '';\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	function check() {\r\n");
      out.write("		if (document.getElementById(\"board_title\").value == \"\") {\r\n");
      out.write("			alert(\"제목을 입력하세요.\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if (document.getElementById(\"price\").value == \"\") {\r\n");
      out.write("			alert(\"가격을 입력하세요\");\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		board_form.submit();\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../top_menu.jsp", out, false);
      out.write("\r\n");
      out.write("	<section style=\"padding-left: 100px; padding-right: 100px;\">\r\n");
      out.write("	<h1 id=\"board_type\" style=\"margin-left: 60px\">상품 등록</h1>\r\n");
      out.write("<div style=\"max-width: 1000px; margin: 0 auto;\">\r\n");
      out.write("	<form class=\"row g-3\" action=\"boardInsertOK.do\" method=\"post\" enctype=\"multipart/form-data\" name=\"board_form\">\r\n");
      out.write("		<div class=\"col-12\">\r\n");
      out.write("			<label for=\"board_title\" class=\"form-label\">제목</label> \r\n");
      out.write("			<input type=\"text\" name=\"board_title\" class=\"form-control\" id=\"board_title\" placeholder=\"제목을 입력하세요\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-12\">\r\n");
      out.write("			<label for=\"price\" class=\"form-label\">가격</label> \r\n");
      out.write("			<input type=\"number\" name=\"price\" class=\"form-control\" id=\"price\" placeholder=\"가격을 입력하세요\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-12\">\r\n");
      out.write("			<label for=\"writer\" class=\"form-label\">작성자</label> \r\n");
      out.write("			<label class=\"form-control\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</label>\r\n");
      out.write("			<input type=\"hidden\" name=\"writer\" class=\"form-control\" id=\"writer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-12\">\r\n");
      out.write("			<label for=\"board_content\" class=\"form-label\">내용</label> \r\n");
      out.write("			<textarea rows=\"20\" cols=\"40\" name=\"board_content\" class=\"form-control\" id=\"board_content\" placeholder=\"내용을 작성하세요\"></textarea>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-md-4\">\r\n");
      out.write("			<label for=\"category\" class=\"form-label\">카테고리</label> \r\n");
      out.write("			<select id=\"category\" name=\"category\" class=\"form-select\">\r\n");
      out.write("				<option selected>디지털기기</option>\r\n");
      out.write("				<option>생활가전</option>\r\n");
      out.write("				<option>가구</option>\r\n");
      out.write("				<option>주방용품</option>\r\n");
      out.write("				<option>유아동</option>\r\n");
      out.write("				<option>의류</option>\r\n");
      out.write("				<option>잡화</option>\r\n");
      out.write("				<option>미용</option>\r\n");
      out.write("				<option>스포츠</option>\r\n");
      out.write("				<option>게임/음반</option>\r\n");
      out.write("				<option>도서</option>\r\n");
      out.write("				<option>티켓</option>\r\n");
      out.write("				<option>가공식품</option>\r\n");
      out.write("				<option>반려동물</option>\r\n");
      out.write("				<option>식물</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-md-4\">\r\n");
      out.write("			<label for=\"deal_region\" class=\"form-label\">거래지역</label> \r\n");
      out.write("			<select id=\"deal_region\" name=\"deal_region\" class=\"form-select\">\r\n");
      out.write("				<option selected>서울</option>\r\n");
      out.write("				<option>부산</option>\r\n");
      out.write("				<option>대구</option>\r\n");
      out.write("				<option>인천</option>\r\n");
      out.write("				<option>광주</option>\r\n");
      out.write("				<option>대전</option>\r\n");
      out.write("				<option>울산</option>\r\n");
      out.write("				<option>강원</option>\r\n");
      out.write("				<option>경기</option>\r\n");
      out.write("				<option>경남</option>\r\n");
      out.write("				<option>경북</option>\r\n");
      out.write("				<option>전남</option>\r\n");
      out.write("				<option>전북</option>\r\n");
      out.write("				<option>제주</option>\r\n");
      out.write("				<option>충남</option>\r\n");
      out.write("				<option>충북</option>\r\n");
      out.write("			</select>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-12\">\r\n");
      out.write("			<input type=\"radio\" name=\"board_type\" id=\"board_type\" value=\"1\" />구해요\r\n");
      out.write("			<input type=\"radio\" name=\"board_type\" id=\"board_type\" value=\"2\" checked=\"checked\" />팔아요\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"col-12\">\r\n");
      out.write("			<label for=\"multipartFiles\" class=\"form-label\">이미지사진</label> \r\n");
      out.write("			<input type=\"file\" name=\"multipartFiles\" id=\"multipartFiles\" multiple=\"multiple\" />\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"col-12\">\r\n");
      out.write("			<input type=\"hidden\" name=\"board_status\" id=\"board_status\" value=\"1\"/>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"col-12\">\r\n");
      out.write("			<input type=\"button\" class=\"btn btn-primary\" value=\"등록\" onclick=\"check()\"/>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
