/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-07-06 05:04:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class selectOne_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/rsm50/Desktop/idle/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/finalAdmin/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1675922414281L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>상세페이지</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("  	<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\" integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js\" integrity=\"sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("	$(function(){\r\n");
      out.write("		console.log('onload...');\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url:\"jsonBoardSelectOne.do\",\r\n");
      out.write("			data:{board_num:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.board_num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("},\r\n");
      out.write("			method:'GET',\r\n");
      out.write("			dataType:'json',\r\n");
      out.write("			success: function(vo2){\r\n");
      out.write("				console.log('ajax success:',vo2);\r\n");
      out.write("				\r\n");
      out.write("				let board_type = ``;\r\n");
      out.write("				if(vo2.board_type==1){\r\n");
      out.write("					board_type = `구해요`;\r\n");
      out.write("				}else{\r\n");
      out.write("					board_type = `팔아요`;\r\n");
      out.write("				}\r\n");
      out.write("				$('#board_type').html(board_type);\r\n");
      out.write("				\r\n");
      out.write("				let img1 = `<img src=\"resources/img/${vo2.board_savename1 }\" height=\"300px\" class=\"d-block w-100\">`;\r\n");
      out.write("				let img2 = `<img src=\"resources/img/${vo2.board_savename2 }\" height=\"300px\" class=\"d-block w-100\">`;\r\n");
      out.write("				let img3 = `<img src=\"resources/img/${vo2.board_savename3 }\" height=\"300px\" class=\"d-block w-100\">`;\r\n");
      out.write("				\r\n");
      out.write("				$('#img1').html(img1);\r\n");
      out.write("				$('#img2').html(img2);\r\n");
      out.write("				$('#img3').html(img3);\r\n");
      out.write("				\r\n");
      out.write("				let board_title = ``;\r\n");
      out.write("				if(vo2.board_status==1){\r\n");
      out.write("					board_title = `판매중 ${vo2.board_title}`;\r\n");
      out.write("				}else{\r\n");
      out.write("					board_title = `판매완료 ${vo2.board_title}`;\r\n");
      out.write("				}\r\n");
      out.write("				$('#board_title').html(board_title);\r\n");
      out.write("				\r\n");
      out.write("				let date = new Date(vo2.board_date).toLocaleString();\r\n");
      out.write("				\r\n");
      out.write("				let board_date = `작성날짜 : ${date}`;\r\n");
      out.write("				$('#board_date').html(board_date);\r\n");
      out.write("				\r\n");
      out.write("				let price = `가격 : ${vo2.price}원`;\r\n");
      out.write("				$('#price').html(price);\r\n");
      out.write("				\r\n");
      out.write("				let category = `카테고리 : ${vo2.category}`;\r\n");
      out.write("				$('#category').html(category);\r\n");
      out.write("				\r\n");
      out.write("				let deal_region = `거래지역 : ${vo2.deal_region}`;\r\n");
      out.write("				$('#deal_region').html(deal_region);\r\n");
      out.write("				\r\n");
      out.write("				let count = `찜 ${vo2.likecount} 채팅 ${vo2.chatcount} 조회 ${vo2.view_count}`;\r\n");
      out.write("				$('#count').html(count);\r\n");
      out.write("				\r\n");
      out.write("				let report_count = `경고횟수 : ${vo2.board_report}`;\r\n");
      out.write("				$('#report_count').html(report_count);\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				let m_img = `<img src=\"resources/img/${vo2.member_savename }\" class=\"d-block w-100\">`;\r\n");
      out.write("				$('#m_img').html(m_img);\r\n");
      out.write("				\r\n");
      out.write("				let m_name = `${vo2.name}`;\r\n");
      out.write("				$('#m_name').html(m_name);\r\n");
      out.write("				\r\n");
      out.write("				let m_address = `${vo2.address}`;\r\n");
      out.write("				$('#m_address').html(m_address);\r\n");
      out.write("				\r\n");
      out.write("				let board_content = `${vo2.board_content}`;\r\n");
      out.write("				$('#board_content').html(board_content);\r\n");
      out.write("				\r\n");
      out.write("				let udbutton = `\r\n");
      out.write("				<a href=\"boardReportUp.do?board_num=${vo2.board_num}\">경고증가</a>\r\n");
      out.write("				<a href=\"boardReportDown.do?board_num=${vo2.board_num}\">경고감소</a>\r\n");
      out.write("				<a href=\"boardDeleteOK.do?board_num=${vo2.board_num}\" onclick=\"return deleteOK()\">삭제</a>\r\n");
      out.write("				`;\r\n");
      out.write("				$('#udbutton').html(udbutton);\r\n");
      out.write("				\r\n");
      out.write("			},\r\n");
      out.write("			error:function(xhr,status,error){\r\n");
      out.write("				console.log('xhr:',xhr.status);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function deleteOK() {\r\n");
      out.write("		  if (confirm(\"정말로 삭제하시겠습니까? 작성자가 울수도 있습니다.\")) {\r\n");
      out.write("		    return true; // 예(확인)를 클릭하면 링크가 진행되어 삭제됨\r\n");
      out.write("		  } else {\r\n");
      out.write("		    return false; // 아니요(취소)를 클릭하면 링크가 취소되어 삭제되지 않음\r\n");
      out.write("		  }\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <section style=\"padding-left: 100px; padding-right: 100px;\">\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../top_menu.jsp", out, false);
      out.write("\r\n");
      out.write("	<h1 id=\"board_type\" ></h1>\r\n");
      out.write("	<div class=\"card mb-3\" style=\"max-width: 100%; \">\r\n");
      out.write("		<div class=\"row g-2\">\r\n");
      out.write("			<div class=\"col-md-4\">\r\n");
      out.write("				<div id=\"carouselExampleControls\" class=\"carousel slide\"\r\n");
      out.write("					data-bs-ride=\"carousel\">\r\n");
      out.write("					<div class=\"carousel-inner\">\r\n");
      out.write("						<div class=\"carousel-item active\" id=\"img1\">\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"carousel-item\" id=\"img2\">\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"carousel-item\" id=\"img3\">\r\n");
      out.write("							\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button class=\"carousel-control-prev\" type=\"button\"\r\n");
      out.write("						data-bs-target=\"#carouselExampleControls\" data-bs-slide=\"prev\">\r\n");
      out.write("						<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("						<span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<button class=\"carousel-control-next\" type=\"button\"\r\n");
      out.write("						data-bs-target=\"#carouselExampleControls\" data-bs-slide=\"next\">\r\n");
      out.write("						<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("						<span class=\"visually-hidden\">Next</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-8\">\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<h4 class=\"card-title\" id=\"board_title\"></h4>\r\n");
      out.write("					<p class=\"card-text\" id=\"board_date\"></p>\r\n");
      out.write("					<p class=\"card-text\" id=\"price\"></p>\r\n");
      out.write("					<p class=\"card-text\" id=\"category\"></p>\r\n");
      out.write("					<p class=\"card-text\" id=\"deal_region\"></p>\r\n");
      out.write("					<p class=\"card-text\" id=\"count\"></p>\r\n");
      out.write("					<p class=\"card-text\" id=\"report_count\"></p>\r\n");
      out.write("					<p class=\"card-text\" id=\"udbutton\"></p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"card mb-3\" style=\"max-width: 200px;\">\r\n");
      out.write("		<div class=\"row g-0\">\r\n");
      out.write("			<div class=\"col-md-4\" id=\"m_img\"></div>\r\n");
      out.write("			<div class=\"col-md-8\">\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<p class=\"card-text\" id=\"m_name\"></p>\r\n");
      out.write("					<p class=\"card-text\" id=\"m_address\"></p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr>\r\n");
      out.write("		<div class=\"form-floating\">\r\n");
      out.write("			<textarea class=\"form-control\" id=\"board_content\" style=\"height: 400px\" readonly></textarea>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
